matrix:
  include:
  - os: osx
    osx_image: xcode8.1
language: c++
install:
- mkdir $TRAVIS_BUILD_DIR/logs
- touch $TRAVIS_BUILD_DIR/logs/build_logs
- touch $TRAVIS_BUILD_DIR/logs/run_logs;
- BUILDLOGS=$TRAVIS_BUILD_DIR/logs/build_logs
- cd $TRAVIS_BUILD_DIR
- echo "***************************** Building externals ****" > $BUILDLOGS
- cd $TRAVIS_BUILD_DIR/examples/pxScene2d/external
- ./build.sh>>$BUILDLOGS
before_script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export DISPLAY=:99.0; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh -e /etc/init.d/xvfb start; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sleep 3; fi
script:
- cd $TRAVIS_BUILD_DIR
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh ./build_linux.sh; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then sh ./build_osx.sh; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh ./testrunner_linux.sh; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then sh ./testrunner_osx.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then cd $TRAVIS_BUILD_DIR; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then tar -cvzf logs.tgz logs/* ; fi
addons:
  ssh_known_hosts: 96.118.6.151
after_script:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then cd $TRAVIS_BUILD_DIR; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./deploy.sh 96.118.6.151 logs.tgz;
  fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then rm -rf /tmp/pxscene-build.pem; fi
before_install:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then openssl aes-256-cbc -K $encrypted_0406ccd56ef2_key -iv $encrypted_0406ccd56ef2_iv
  -in pxscene-build.pem.enc -out /tmp/pxscene-build.pem -d ; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install git libglew-dev freeglut3
  freeglut3-dev libgcrypt11-dev zlib1g-dev g++ libssl-dev nasm autoconf; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then eval "$(ssh-agent -s)"; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then  chmod 600 /tmp/pxscene-build.pem;
  fi
cache: ccache
